name: goreleaser

on:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Make All
        run: |
          sudo bash package.sh
          

      - name: Push To git
        run: |
          pwd
          echo "Directory"
          pwd
          git config user.name "Your Name Here"
          git config user.email your@email.com
          git config advice.addIgnoredFile false
          git add -f *
          git commit -m "All"
          git push
